In [2]:
from sklearn import preprocessing
import numpy as np

In [3]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [4]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_stand = standardizer.fit_transform(X_train)
X_train_stand 

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [6]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [7]:
# Aplicamos los métodos "fit" y "transform" por separado
# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = standardizer.fit(X_train_2)
print(f)

X_train_stand_2 = f.transform(X_train)
X_train_stand_2

StandardScaler()


array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [8]:
# Comprobar si las matrices estandarizadas son iguales
X_train_stand_2 == X_train_stand

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
X_test = np.array([[1., 0., 1.5]])
X_test_stand= f.transform(X_test)
X_test_stand

array([[0.        , 0.        , 0.93541435]])